name: Feature Request
description: File a feature request.
title: '[Feature]: '
labels: ['enhancement', 'needs-triage']
assignees: []
type: enhancement
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      placeholder: Describe the feature you want or need
      value: I need the software to do this.
    validations:
      required: true
  - type: textarea
    id: benefits
    attributes:
      label: What are the benefits of this feature?
      placeholder: Describe the advantages of having this feature
      value: The benefits of this feature include...
    validations:
      required: true
